/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DeviceManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DeviceManagementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author linlinfan
 */
public class DeviceMngWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DeviceManagementOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network netWork;
   

    /**
     * Creates new form DeviceMngWorkAreaJPanel
     */
    public DeviceMngWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DeviceManagementOrganization organization,
           Enterprise enterprise, Network netWork, EcoSystem business) {
        initComponents();
                
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.netWork = netWork;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnManageDeviceInventory = new javax.swing.JButton();
        btnManageDeviceReceipt = new javax.swing.JButton();
        btnManageMedicalDevicesReservation = new javax.swing.JButton();
        btnProcessDeviceReservationRequests = new javax.swing.JButton();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");

        valueLabel.setText("<value>");

        btnManageDeviceInventory.setText("Manage Devices Inventory");
        btnManageDeviceInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeviceInventoryActionPerformed(evt);
            }
        });

        btnManageDeviceReceipt.setText("Manage Device Receipt");
        btnManageDeviceReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeviceReceiptActionPerformed(evt);
            }
        });

        btnManageMedicalDevicesReservation.setText("Manage Medical Devices Reservation");
        btnManageMedicalDevicesReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMedicalDevicesReservationActionPerformed(evt);
            }
        });

        btnProcessDeviceReservationRequests.setText("Process Device Reservation Requests");
        btnProcessDeviceReservationRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessDeviceReservationRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(536, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnManageDeviceInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnManageMedicalDevicesReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(84, 84, 84)))
                    .addComponent(btnManageDeviceReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(btnProcessDeviceReservationRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageDeviceInventory, btnManageDeviceReceipt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(btnManageMedicalDevicesReservation)
                .addGap(52, 52, 52)
                .addComponent(btnProcessDeviceReservationRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(btnManageDeviceInventory)
                .addGap(52, 52, 52)
                .addComponent(btnManageDeviceReceipt)
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDeviceInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeviceInventoryActionPerformed
        // TODO add your handling code here:
           ManageDevicesInventoryJPanel manageInventoryJPanel = new ManageDevicesInventoryJPanel(userProcessContainer, userAccount, organization,
                enterprise);
        userProcessContainer.add("manageRoomsJPanel", manageInventoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDeviceInventoryActionPerformed

    private void btnManageDeviceReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeviceReceiptActionPerformed
        // TODO add your handling code here:
//        DeviceManagementOrganization deviceOrg = (DeviceManagementOrganization) organization;
        ManageDeviceReceiptJPanel managedevicereceiptJPanel = new ManageDeviceReceiptJPanel(userProcessContainer, userAccount, organization, enterprise, business); 
        userProcessContainer.add("ManageDeviceReceiptJPanel", managedevicereceiptJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
   
    }//GEN-LAST:event_btnManageDeviceReceiptActionPerformed

    private void btnManageMedicalDevicesReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMedicalDevicesReservationActionPerformed
        // TODO add your handling code here:

        ManageMedicalDevicesReservJPanel managedevicessJPanel = new ManageMedicalDevicesReservJPanel(userProcessContainer,
                userAccount, organization, enterprise, netWork, business);
        userProcessContainer.add("manageMedicalDeviceReservJPanel", managedevicessJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageMedicalDevicesReservationActionPerformed

    private void btnProcessDeviceReservationRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessDeviceReservationRequestsActionPerformed
        ProcessDeviceReservationRequestsJPanel processDeviceReservationJPanel = new ProcessDeviceReservationRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, business); // 可能需要 business 对象
        userProcessContainer.add("ManageDeviceReservationRequestsJPanel", processDeviceReservationJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessDeviceReservationRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDeviceInventory;
    private javax.swing.JButton btnManageDeviceReceipt;
    private javax.swing.JButton btnManageMedicalDevicesReservation;
    private javax.swing.JButton btnProcessDeviceReservationRequests;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
