/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DeviceManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.DeviceManagementOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DeviceReservationWorkRequest;
import Business.WorkQueue.OperationsRoomReservationWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.models.device.Device;
import Business.models.device.DeviceDirectory;
import Business.models.room.Room;
import Business.models.room.RoomDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajath
 */
;public class ProcessReservationWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessReservationWorkRequestJPanel
     */
    

//    private DeviceReservationWorkRequest request;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DeviceManagementOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network netWork;
    private DeviceReservationWorkRequest selectedRequest;
    
    public ProcessReservationWorkRequestJPanel(JPanel userProcessContainer, UserAccount account, DeviceReservationWorkRequest request, DeviceManagementOrganization organization, Enterprise enterprise, Network netWork, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.selectedRequest = request;
        this.organization = organization;
        this.enterprise = (HospitalEnterprise) enterprise;
        this.userAccount = account;
        this.netWork = netWork;
        this.business = business;  
        
        populateTable();
        
    }  
    
        public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
//        DeviceReservationWorkRequest reservationRequest = (DeviceReservationWorkRequest) request;
System.out.println("Request device name: " + selectedRequest.getDeviceName());
System.out.println(organization.getDevices( selectedRequest));

        
        for(Device device : organization.getDevices( selectedRequest)){     
            Object[] row = new Object[6];
            row[0] = device;
            row[1] = device.getDeviceID();
            row[2] = device.getType();
            row[3] = device.getManufacturer();
            row[4] = device.isAvailable();
            row[5] = device.getYearofManufacturing();
             
            model.addRow(row);
            System.out.println(device.getYearofManufacturing());
     
    }
        }
          
        
    
//    private void populateRoomComboBox() {
//        deviceJComboBox.removeAllItems();
//        
//        DeviceDirectory deviceDirectory = ((HospitalEnterprise) enterprise).getDeviceDirectory();
//        for (Device  device: deviceDirectory.getDeviceList()) {
//            if (device.isAvailable()) {  // Only add available device
//                deviceJComboBox.addItem(device);
//            }
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnApprove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnFindSupplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnFindSupplier.setText("Find Supplier");
        btnFindSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindSupplierActionPerformed(evt);
            }
        });

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Device", "DeviceID", "Type", "Manufacture", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnApprove)
                            .addComponent(btnBack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 592, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFindSupplier, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindSupplier)
                    .addComponent(btnApprove))
                .addGap(135, 135, 135))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
         int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow >= 0){
            Device selectedDevice = (Device) workRequestJTable.getValueAt(selectedRow, 0);
//            organization.approveDeviceReservation(selectedDevice, selectedRequest);

        if (selectedRequest != null) {
//            organization.approveDeviceReservation(selectedDevice, selectedRequest);
            selectedRequest.setStatus(WorkRequest.Status.Completed);
            selectedRequest.setDeviceID(selectedDevice.getDeviceID());
            selectedDevice.setAvailable(false);
            
            JOptionPane.showMessageDialog(null, "Device approved successfully!");
            
            // Refresh table to reflect changes
            populateTable(); 
            
        } else {
        JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
    }
        
           
        } else {
            JOptionPane.showMessageDialog(null, "Please select a device from the list to view.", "Warning", JOptionPane.WARNING_MESSAGE);
        
        }
        
       
     
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageMedicalDevicesReservJPanel dwjp = (ManageMedicalDevicesReservJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnFindSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindSupplierActionPerformed
        // TODO add your handling code here:
        
//        int selectedRow = workRequestJTable.getSelectedRow();
//
//        if (selectedRow < 0){
//            return;
//        }

//        Device selectedDevice = (Device)workRequestJTable.getValueAt(selectedRow, 0);
//      
        
        FindSupplierJPanel findSupplierJPanel = new FindSupplierJPanel(userProcessContainer,
                userAccount, selectedRequest, organization, enterprise, netWork, business);
        userProcessContainer.add("manageMedicalDeviceReservJPanel", findSupplierJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        


    }//GEN-LAST:event_btnFindSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFindSupplier;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
