//package ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


package ui.SupplierRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;

import Business.Enterprise.Enterprise;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import Business.models.device.Device;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;


import javax.swing.JPanel;

/**
 *
 * @author linlinfan
 */
public class CreateNewDeviceJPanel extends javax.swing.JPanel {

    /** Creates new form CreateNewProductJPanel */
    JPanel userProcessContainer;
    Enterprise enterprise;
    SupplierOrganization organization;
    UserAccount userAccount;

    
    
    public CreateNewDeviceJPanel(JPanel userProcessContainer, SupplierOrganization organization, UserAccount account, Enterprise enterprise){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = account;
        
        txtAvailability.setText("0");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAvailability = new javax.swing.JTextField();
        lblProductAvail = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblProductName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblProductID = new javax.swing.JLabel();
        lblCreateNewProduct = new javax.swing.JLabel();

        txtAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailabilityActionPerformed(evt);
            }
        });

        lblProductAvail.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblProductAvail.setText("Device Availability ((number of units in stock):):");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblProductName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblProductName.setText("Device Name:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAdd.setText("Add Device");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        lblProductID.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblProductID.setText("Device ID:");

        lblCreateNewProduct.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCreateNewProduct.setText("Create New Device");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack)
                        .addGap(132, 132, 132)
                        .addComponent(lblCreateNewProduct))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProductAvail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProductName)
                            .addComponent(lblProductID))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAvailability, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(322, 322, 322))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblCreateNewProduct))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        backAction();
    }
    private void backAction(){
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDeviceCatalogJPanel manageProductCatalogJPanel = (ManageDeviceCatalogJPanel) component;
        manageProductCatalogJPanel.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

//        double price = 0.0;
        int quantity = 0;
        String availText = txtAvailability.getText().trim();

        try {
//            price = Double.parseDouble(txtPrice.getText());
            // quantity = Integer.parseInt(txtAvailability.getText());
            quantity = Integer.parseInt(availText);
            if (quantity < 0 ) {
                JOptionPane.showMessageDialog(this, "Device Availability must be **0 or greater**","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Device Availability must be a valid number","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
//        String name = userAccount.getUsername();
//        SupplierOrganization supplierOrg = (SupplierOrganization) organization;
//        
//        ArrayList<Device> matchingDevices = new ArrayList<>(supplierOrg.findDevicesByManufacturerName(name));
//        
//        Device d = new Device();
//        matchingDevices.add(d);
        String deviceName = txtName.getText().trim();
        if (deviceName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Device Name cannot be empty","Warning", JOptionPane.WARNING_MESSAGE);
        }
       
        Device d = organization.getDeviceDirectory().addNewDevice();
        d.setName(txtName.getText());
        d.setAvailability(quantity);
        d.setManufacturer(userAccount.getUsername());
        
//        DB4OUtil.getInstance().storeSystem(system);
   
        JOptionPane.showMessageDialog(this, "Device added successfully!", "Info", JOptionPane.INFORMATION_MESSAGE);

        txtName.setText("");
        txtAvailability.setText("");
        //
        //        Product p = supplier.getProductCatalog().addProduct();
        //        p.setProdName(txtName.getText());
        //        String stringPrice = txtPrice.getText();
        //        if(stringPrice.isEmpty()==false){
            //            int price = Integer.parseInt(stringPrice);
            //            p.setPrice(price);
            //        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void txtAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailabilityActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblCreateNewProduct;
    private javax.swing.JLabel lblProductAvail;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
