/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MaintainerRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.MaintenanceOrganization;
import Business.Organization.OperationsManagementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.models.device.Device;
import Business.models.device.DeviceDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajath
 */
public class MaintainDevicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MaintainDevicesJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private MaintenanceOrganization maintainenceOrganization;
    private Enterprise enterprise;
    public MaintainDevicesJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.maintainenceOrganization = (MaintenanceOrganization) maintainenceOrganization;
        this.enterprise = enterprise;
        populateDevicesTable();
    }
    
    public void populateDevicesTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setRowCount(0);
        
        // Add this custom renderer to color rows
        workRequestJTable.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String lastMaintenanceStr = (String) table.getValueAt(row, 7); // Last maintenance column
                
                if(lastMaintenanceStr == null || lastMaintenanceStr.equals("N/A")) {
                    c.setBackground(table.getBackground());
                    return c;
                }
                
                try {
                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
                    java.util.Date lastMaintenance = sdf.parse(lastMaintenanceStr);
                    java.util.Date now = new java.util.Date();
                    long diffInMillies = now.getTime() - lastMaintenance.getTime();
                    long diffInMonths = diffInMillies / (30L * 24L * 60L * 60L * 1000L);
                    
                    if (diffInMonths >= 6) {
                        c.setBackground(java.awt.Color.RED);
                    } else if (diffInMonths >= 4) {
                        c.setBackground(java.awt.Color.ORANGE);
                    } else if (diffInMonths >= 2) {
                        c.setBackground(java.awt.Color.YELLOW);
                    } else {
                        c.setBackground(table.getBackground());
                    }
                } catch (java.text.ParseException e) {
                    c.setBackground(table.getBackground());
                }
                return c;
            }
        });

        DeviceDirectory deviceDirectory = ((HospitalEnterprise) enterprise).getDeviceDirectory();
        
        for (Device device : deviceDirectory.getDeviceList()) {
            Object[] row = new Object[8];
            row[0] = device;
            row[1] = device.getName();
            row[2] = device.getType();
            row[3] = device.getManifacturer();
            row[4] = device.getCurrentLocation();
            row[5] = device.getIsPortable();
            row[6] = device.isAvailable();
            row[7] = device.getLastMaintenanceDate() != null ? device.getLastMaintenanceDate() : "N/A";
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        requestOperationsRoomJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        requestOperationsRoomJButton.setText("Update device");
        requestOperationsRoomJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestOperationsRoomJButtonActionPerformed(evt);
            }
        });

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Device ID", "Name", "Type", "Manifacturer", "Location", "Portable", "Available", "Last Maintainence"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(requestOperationsRoomJButton)
                        .addGap(26, 26, 26)
                        .addComponent(refreshTestJButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshTestJButton)
                    .addComponent(requestOperationsRoomJButton)
                    .addComponent(btnBack))
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateDevicesTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void requestOperationsRoomJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestOperationsRoomJButtonActionPerformed
 
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            Device selectedDevice = (Device) workRequestJTable.getValueAt(selectedRow, 0);    
            
            if(selectedDevice == null) {
                JOptionPane.showMessageDialog(null, "Invalid device selection", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("UpdateDeviceJPanel", new UpdateDeviceJPanel(userProcessContainer, selectedDevice));
            layout.next(userProcessContainer);
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select a book from the list view.", "Warning", JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_requestOperationsRoomJButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestOperationsRoomJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
