/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PHSAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BundleReservationWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.models.device.Device;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Administrator
 */
public class PHSAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PHSAdminWorkAreaJPanel1
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    
    public PHSAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        
        lblValue.setText(enterprise.getName());
        hideTableColumn(tblBundleRequests, 0);
        populateTable();
        
    }
    
    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblBundleRequests.getModel();
        model.setRowCount(0); 

        if (organization == null || organization.getWorkQueue() == null) {
            System.err.println("PHSAdminOrganization or its WorkQueue is null. Cannot populate requests.");
            return;
        }


        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {

            if (request instanceof BundleReservationWorkRequest) {
                BundleReservationWorkRequest bundleRequest = (BundleReservationWorkRequest) request;

                Object[] row = new Object[7];

                row[0] = bundleRequest;
                row[1] = bundleRequest.getPatientName();
                row[2] = bundleRequest.getPatientID();
                row[3] = bundleRequest.getSurgeryType();
                row[4] = bundleRequest.getRequiredDate();
                row[5] = getDeviceInfoFromRequest(bundleRequest);
                row[6] = bundleRequest.getStatus(); 

                model.addRow(row);
            }
        }
    }
    
    private String getDeviceInfoFromRequest(BundleReservationWorkRequest request) {
        if (request == null) {
            return "None";
        }

        StringBuilder devices = new StringBuilder();

        boolean daVinciSelected = false;

        if (request.getResourceBundle() != null && 
            request.getResourceBundle().getRequiredDevices() != null) {

            for (Device device : request.getResourceBundle().getRequiredDevices()) {
                if (device != null && device.getName().toLowerCase().contains("davinci")) {
                    daVinciSelected = true;
                    break;
                }
            }

            if (daVinciSelected) {
                devices.append("DaVinci Console, DaVinci Vision Cart, DaVinci Arms Set");
            }

            for (Device device : request.getResourceBundle().getRequiredDevices()) {
                if (device != null && !device.getName().toLowerCase().contains("davinci")) {
                    if (devices.length() > 0) {
                        devices.append(", ");
                    }
                    devices.append(device.getName());
                }
            }
        }

        return devices.length() > 0 ? devices.toString() : "None";
    }

    private void hideTableColumn(javax.swing.JTable table, int columnIndex) {
        if (table != null && table.getColumnModel().getColumnCount() > columnIndex && columnIndex >= 0) {
           TableColumn column = table.getColumnModel().getColumn(columnIndex);
           column.setMinWidth(0);
           column.setMaxWidth(0);
           column.setWidth(0);
           column.setPreferredWidth(0);
        } else {
            System.err.println("Error hiding column " + columnIndex + " for table " + (table != null ? table.getName() : "null"));
        }
    }
    
    public Organization getOrganization() {
        return this.organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterprise = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnProcessRequest = new javax.swing.JButton();
        lblBundleRequests = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBundleRequests = new javax.swing.JTable();

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise.setText("EnterPrise :");

        lblValue.setText("<value>");

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTitle.setText("PHS Admin WorkArea");

        btnProcessRequest.setText("Process Selected Request");
        btnProcessRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestActionPerformed(evt);
            }
        });

        lblBundleRequests.setText("Bundle Requests:");

        tblBundleRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Request Object", "Patient Name", "Patient ID", "Surgery Type", "Required Date", "Required Device(s)", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblBundleRequests);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBundleRequests)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProcessRequest)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTitle)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblValue)))
                .addGap(18, 18, 18)
                .addComponent(lblBundleRequests)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProcessRequest)
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestActionPerformed

        int selectedRowIndex = tblBundleRequests.getSelectedRow();

        if (selectedRowIndex < 0) {

            JOptionPane.showMessageDialog(this, "Please select a request from the table first.", "No Request Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        BundleReservationWorkRequest requestToProcess = null;
        Object requestObject = tblBundleRequests.getValueAt(selectedRowIndex, 0);

        if (requestObject instanceof BundleReservationWorkRequest) {
             requestToProcess = (BundleReservationWorkRequest) requestObject;
        } else {

             JOptionPane.showMessageDialog(this, "Error: Could not retrieve valid request data from the selected row.", "Data Error", JOptionPane.ERROR_MESSAGE);
             System.err.println("Object in hidden column is not a BundleReservationWorkRequest or is null.");
             return;
        }

        String currentStatus = requestToProcess.getStatusString();
        if (!"Submitted to PHS".equalsIgnoreCase(currentStatus)) {
            JOptionPane.showMessageDialog(this, "This request is currently in '" + currentStatus + "' status and cannot be processed now.", "Request Status", JOptionPane.INFORMATION_MESSAGE);
            return; 
        }

        CreateResourceBundlesJPanel createResourceBundlesJPanel = new CreateResourceBundlesJPanel(
                userProcessContainer, 
                userAccount,
                enterprise,
                business,
                requestToProcess
        );

        userProcessContainer.add("CreateResourceBundlesJPanel_Process", createResourceBundlesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessRequestActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBundleRequests;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTable tblBundleRequests;
    // End of variables declaration//GEN-END:variables
}
