/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author rajath, Di
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        
        
        if (userAccount != null && userAccount.getEmployee() != null) {
            lblValue.setText("Welcome, " + userAccount.getEmployee().getName() + "!");
        } else {
            lblValue.setText("Welcome!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnRequestResourceBundle = new javax.swing.JButton();
        btnViewMyBundleRequests = new javax.swing.JButton();
        btnManageOperationsRoomsRequests = new javax.swing.JButton();
        btnManageDeviceRequests = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Doctor WorkArea");

        lblValue.setText("<value>");

        btnRequestResourceBundle.setText("Request Resource Bundle");
        btnRequestResourceBundle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestResourceBundleActionPerformed(evt);
            }
        });

        btnViewMyBundleRequests.setText("View My Bundle Request");
        btnViewMyBundleRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMyBundleRequestsActionPerformed(evt);
            }
        });

        btnManageOperationsRoomsRequests.setText("Manage Operations Rooms Request");
        btnManageOperationsRoomsRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOperationsRoomsRequestsActionPerformed(evt);
            }
        });

        btnManageDeviceRequests.setText("Manage Medical Device Request");
        btnManageDeviceRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeviceRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewMyBundleRequests)
                            .addComponent(btnRequestResourceBundle)
                            .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageDeviceRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageOperationsRoomsRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(203, 203, 203))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageDeviceRequests, btnManageOperationsRoomsRequests, btnRequestResourceBundle, btnViewMyBundleRequests});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnRequestResourceBundle)
                .addGap(18, 18, 18)
                .addComponent(btnViewMyBundleRequests)
                .addGap(29, 29, 29)
                .addComponent(btnManageOperationsRoomsRequests)
                .addGap(18, 18, 18)
                .addComponent(btnManageDeviceRequests)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnManageDeviceRequests, btnManageOperationsRoomsRequests, btnRequestResourceBundle, btnViewMyBundleRequests});

    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestResourceBundleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestResourceBundleActionPerformed
        RequestResourceBundleJPanel requestBundleJPanel = new RequestResourceBundleJPanel(userProcessContainer, userAccount, enterprise, business); // 传入 business 对象
        userProcessContainer.add("RequestBundleJPanel", requestBundleJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestResourceBundleActionPerformed

    private void btnViewMyBundleRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMyBundleRequestsActionPerformed
        ViewBundleRequestsJPanel viewBundleRequestsJPanel = new ViewBundleRequestsJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("ViewBundleRequestsJPanel", viewBundleRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewMyBundleRequestsActionPerformed

    private void btnManageOperationsRoomsRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOperationsRoomsRequestsActionPerformed
        ManageOperationsJPanel manageOperationsJPanel=new ManageOperationsJPanel(userProcessContainer, userAccount, organization, enterprise);
        userProcessContainer.add("manageOperationsJPanel",manageOperationsJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOperationsRoomsRequestsActionPerformed

    private void btnManageDeviceRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeviceRequestsActionPerformed
        ManageDevicesJPanel manageDevicesJPanel=new ManageDevicesJPanel(userProcessContainer, userAccount, organization, enterprise);
        userProcessContainer.add("manageDevicesJPanel",manageDevicesJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDeviceRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDeviceRequests;
    private javax.swing.JButton btnManageOperationsRoomsRequests;
    private javax.swing.JButton btnRequestResourceBundle;
    private javax.swing.JButton btnViewMyBundleRequests;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
